export type Player = {
  name: string;
  country: string;
};

const SQUADS: Record<string, string[]> = {
  Argentina: [
    "Lionel Messi",
    "Lautaro Martínez",
    "Julián Álvarez",
    "Ángel Di María",
    "Paulo Dybala",
    "Enzo Fernández",
    "Alexis Mac Allister",
    "Rodrigo De Paul",
    "Emiliano Martínez",
    "Cristian Romero",
    "Nicolás Otamendi",
    "Giovani Lo Celso",
    "Nicolás González",
    "Leandro Paredes",
    "Germán Pezzella",
  ],
  Australia: [
    "Mathew Ryan",
    "Harry Souttar",
    "Aaron Mooy",
    "Mitchell Duke",
    "Mathew Leckie",
    "Jackson Irvine",
    "Craig Goodwin",
    "Riley McGree",
    "Martin Boyle",
    "Ajdin Hrustic",
    "Aziz Behich",
    "Bailey Wright",
  ],
  Austria: [
    "David Alaba",
    "Marcel Sabitzer",
    "Konrad Laimer",
    "Marko Arnautović",
    "Christoph Baumgartner",
    "Florian Grillitsch",
    "Philipp Lienhart",
    "Stefan Posch",
    "Romano Schmid",
    "Patrick Wimmer",
    "Michael Gregoritsch",
    "Alexander Schlager",
  ],
  Belgium: [
    "Kevin De Bruyne",
    "Romelu Lukaku",
    "Jeremy Doku",
    "Youri Tielemans",
    "Thibaut Courtois",
    "Amadou Onana",
    "Charles De Ketelaere",
    "Loïs Openda",
    "Arthur Theate",
    "Timothy Castagne",
    "Leandro Trossard",
    "Dodi Lukebakio",
  ],
  Brazil: [
    "Vinícius Júnior",
    "Rodrygo",
    "Raphinha",
    "Neymar",
    "Endrick",
    "Richarlison",
    "Bruno Guimarães",
    "Casemiro",
    "Lucas Paquetá",
    "Alisson",
    "Marquinhos",
    "Gabriel Magalhães",
    "Danilo",
    "Éder Militão",
    "Raphinha",
    "Pedro",
    "Estêvão",
  ],
  Canada: [
    "Alphonso Davies",
    "Jonathan David",
    "Cyle Larin",
    "Sam Adekugbe",
    "Stephen Eustáquio",
    "Liam Millar",
    "Tajon Buchanan",
    "Ismaël Koné",
    "Richie Laryea",
    "Derek Cornelius",
    "Milan Borjan",
    "Jacob Shaffelburg",
  ],
  Colombia: [
    "James Rodríguez",
    "Luis Díaz",
    "Radamel Falcao",
    "Jhon Durán",
    "Jefferson Lerma",
    "Davinson Sánchez",
    "Yerry Mina",
    "Juan Cuadrado",
    "Luis Sinisterra",
    "Santiago Arias",
    "Camilo Vargas",
    "Jhon Arias",
  ],
  Croatia: [
    "Luka Modrić",
    "Mateo Kovačić",
    "Bruno Petković",
    "Ivan Perišić",
    "Joško Gvardiol",
    "Marko Livaja",
    "Nikola Vlašić",
    "Marcelo Brozović",
    "Dominik Livaković",
    "Mario Pašalić",
    "Ante Budimir",
    "Borna Sosa",
  ],
  Denmark: [
    "Christian Eriksen",
    "Rasmus Højlund",
    "Pierre-Emile Højbjerg",
    "Andreas Skov Olsen",
    "Joakim Mæhle",
    "Mikkel Damsgaard",
    "Kasper Schmeichel",
    "Alexander Bah",
    "Victor Nelsson",
    "Yussuf Poulsen",
    "Mattias Jensen",
    "Jonas Wind",
  ],
  Ecuador: [
    "Enner Valencia",
    "Moises Caicedo",
    "Pervis Estupiñán",
    "Kendry Páez",
    "Piero Hincapié",
    "Jeremy Sarmiento",
    "Ángel Mena",
    "Alexander Domínguez",
    "Felix Torres",
    "Carlos Gruezo",
    "Willian Pacho",
    "Jordy Caicedo",
  ],
  Egypt: [
    "Mohamed Salah",
    "Omar Marmoush",
    "Trézéguet",
    "Mohamed Elneny",
    "Ahmed Hegazi",
    "Mohamed Abdelmonem",
    "Mahmoud Hassan",
    "Mohamed Sherif",
    "Mohamed El Shenawy",
    "Emam Ashour",
    "Marwan Hamdy",
    "Mostafa Mohamed",
  ],
  England: [
    "Harry Kane",
    "Jude Bellingham",
    "Phil Foden",
    "Bukayo Saka",
    "Declan Rice",
    "Cole Palmer",
    "Ollie Watkins",
    "Anthony Gordon",
    "Trent Alexander-Arnold",
    "John Stones",
    "Jordan Pickford",
    "Kobbie Mainoo",
    "Marcus Rashford",
    "Jack Grealish",
    "Mason Mount",
    "Kieran Trippier",
  ],
  France: [
    "Kylian Mbappé",
    "Antoine Griezmann",
    "Ousmane Dembélé",
    "Aurélien Tchouaméni",
    "Eduardo Camavinga",
    "William Saliba",
    "Dayot Upamecano",
    "Hugo Lloris",
    "Olivier Giroud",
    "Kingsley Coman",
    "Randal Kolo Muani",
    "Bradley Barcola",
    "Warren Zaïre-Emery",
    "Ibrahima Konaté",
    "Theo Hernandez",
    "Marcus Thuram",
  ],
  Germany: [
    "Jamal Musiala",
    "Florian Wirtz",
    "Kai Havertz",
    "Leroy Sané",
    "Niclas Füllkrug",
    "Joshua Kimmich",
    "İlkay Gündoğan",
    "Antonio Rüdiger",
    "Manuel Neuer",
    "Serge Gnabry",
    "Timo Werner",
    "Jonathan Tah",
    "Maximilian Mittelstädt",
    "Deniz Undav",
    "Nico Schlotterbeck",
  ],
  Ghana: [
    "Mohammed Kudus",
    "Thomas Partey",
    "Jordan Ayew",
    "André Ayew",
    "Inaki Williams",
    "Mohammed Salisu",
    "Daniel Amartey",
    "Lawrence Ati-Zigi",
    "Antoine Semenyo",
    "Ernest Nuamah",
    "Osman Bukari",
    "Alexander Djiku",
  ],
  Iran: [
    "Mehdi Taremi",
    "Sardar Azmoun",
    "Alireza Jahanbakhsh",
    "Milad Mohammadi",
    "Saeid Ezatolahi",
    "Alireza Beiranvand",
    "Rouzbeh Cheshmi",
    "Mehdi Ghoddos",
    "Vahid Amiri",
    "Karim Ansarifard",
    "Omid Noorafkan",
    "Shojae Khalilzadeh",
  ],
  Italy: [
    "Federico Chiesa",
    "Nicolò Barella",
    "Gianluigi Donnarumma",
    "Alessandro Bastoni",
    "Federico Dimarco",
    "Giacomo Raspadori",
    "Matteo Politano",
    "Davide Frattesi",
    "Rafael Leão",
    "Lorenzo Pellegrini",
    "Alessio Romagnoli",
    "Gianluca Scamacca",
  ],
  Japan: [
    "Kaoru Mitoma",
    "Takefusa Kubo",
    "Daichi Kamada",
    "Wataru Endo",
    "Hiroki Ito",
    "Ritsu Doan",
    "Ayase Ueda",
    "Junya Ito",
    "Yuki Soma",
    "Ko Itakura",
    "Shuichi Gonda",
    "Daizen Maeda",
  ],
  Mexico: [
    "Raúl Jiménez",
    "Hirving Lozano",
    "Edson Álvarez",
    "Luis Chávez",
    "Guillermo Ochoa",
    "Orbelín Pineda",
    "Santiago Giménez",
    "Jesús Corona",
    "César Montes",
    "Jorge Sánchez",
    "Luis Romo",
    "Uriel Antuna",
  ],
  Morocco: [
    "Achraf Hakimi",
    "Youssef En-Nesyri",
    "Sofyan Amrabat",
    "Hakim Ziyech",
    "Brahim Díaz",
    "Noussair Mazraoui",
    "Sofiane Boufal",
    "Azzedine Ounahi",
    "Nayef Aguerd",
    "Yahya Attiat-Allah",
    "Bono",
    "Selim Amallah",
  ],
  Netherlands: [
    "Virgil van Dijk",
    "Memphis Depay",
    "Cody Gakpo",
    "Frenkie de Jong",
    "Steven Bergwijn",
    "Denzel Dumfries",
    "Matthijs de Ligt",
    "Xavi Simons",
    "Brian Brobbey",
    "Jeremie Frimpong",
    "Mark Flekken",
    "Daley Blind",
    "Wout Weghorst",
    "Tijjani Reijnders",
  ],
  Norway: [
    "Erling Haaland",
    "Martin Ødegaard",
    "Alexander Sørloth",
    "Sander Berge",
    "Antoine Semenyo",
    "Kristoffer Ajer",
    "Felix Myhre",
    "André Hansen",
    "Julian Ryerson",
    "Aron Dønnum",
    "Patrick Berg",
    "Oscar Bobb",
  ],
  Poland: [
    "Robert Lewandowski",
    "Piotr Zieliński",
    "Wojciech Szczęsny",
    "Kamil Glik",
    "Sebastian Szymański",
    "Nicola Zalewski",
    "Jakub Kiwior",
    "Krzysztof Piątek",
    "Przemysław Frankowski",
    "Bartosz Slisz",
    "Karol Świderski",
    "Mateusz Klich",
  ],
  Portugal: [
    "Cristiano Ronaldo",
    "Bernardo Silva",
    "Bruno Fernandes",
    "Rafael Leão",
    "Diogo Jota",
    "João Félix",
    "Rúben Dias",
    "Pepe",
    "João Cancelo",
    "Diogo Costa",
    "Vitinha",
    "Gonçalo Ramos",
    "Pedro Neto",
    "Nuno Mendes",
    "Otávio",
  ],
  Qatar: [
    "Almoez Ali",
    "Akram Afif",
    "Hassan Al-Haydos",
    "Boualem Khoukhi",
    "Abdelkarim Hassan",
    "Youssef Msakni",
    "Karim Boudiaf",
    "Saad Al-Sheeb",
    "Pedro Miguel",
    "Bassam Al-Rawi",
    "Homam Ahmed",
    "Mohammed Muntari",
  ],
  "Saudi Arabia": [
    "Salem Al-Dawsari",
    "Firas Al-Buraikan",
    "Saud Abdulhamid",
    "Mohammed Al-Owais",
    "Ali Al-Bulaihi",
    "Sami Al-Najei",
    "Abdulellah Al-Malki",
    "Hassan Tambakti",
    "Saleh Al-Shehri",
    "Nawaf Al-Abed",
    "Sultan Al-Ghannam",
    "Ayman Yahya",
  ],
  Senegal: [
    "Sadio Mané",
    "Nicolas Jackson",
    "Ismaïla Sarr",
    "Kalidou Koulibaly",
    "Idrissa Gueye",
    "Pape Matar Sarr",
    "Moussa Niakhaté",
    "Édouard Mendy",
    "Boulaye Dia",
    "Formose Mendy",
    "Cheikhou Kouyaté",
    "Habib Diallo",
  ],
  Serbia: [
    "Aleksandar Mitrović",
    "Dušan Vlahović",
    "Sergej Milinković-Savić",
    "Filip Kostić",
    "Nemanja Matić",
    "Nikola Milenković",
    "Andrija Živković",
    "Vanja Milinković-Savić",
    "Strahinja Pavlović",
    "Saša Lukić",
    "Luka Jović",
    "Mihailo Ristić",
  ],
  "South Korea": [
    "Son Heung-min",
    "Lee Kang-in",
    "Hwang Hee-chan",
    "Kim Min-jae",
    "Cho Gue-sung",
    "Jung Woo-young",
    "Hwang Ui-jo",
    "Paik Seung-ho",
    "Hong Hyun-seok",
    "Kim Young-gwon",
    "Jo Hyeon-woo",
    "Yang Hyun-jun",
  ],
  Spain: [
    "Lamine Yamal",
    "Nico Williams",
    "Pedri",
    "Gavi",
    "Álvaro Morata",
    "Dani Olmo",
    "Rodri",
    "Ferran Torres",
    "Mikel Oyarzabal",
    "Unai Simón",
    "Aymeric Laporte",
    "Joselu",
    "Fabián Ruiz",
    "Marc Cucurella",
    "Yeremy Pino",
  ],
  Switzerland: [
    "Granit Xhaka",
    "Breel Embolo",
    "Xherdan Shaqiri",
    "Manuel Akanji",
    "Fabian Schär",
    "Remo Freuler",
    "Ricardo Rodríguez",
    "Yann Sommer",
    "Dan Ndoye",
    "Ruben Vargas",
    "Michel Aebischer",
    "Steven Zuber",
  ],
  Tunisia: [
    "Wahbi Khazri",
    "Youssef Msakni",
    "Ellyes Skhiri",
    "Aymen Dahmen",
    "Naim Sliti",
    "Hamza Mathlouthi",
    "Montassar Talbi",
    "Ferjani Sassi",
    "Issam Jebali",
    "Anis Ben Slimane",
    "Ali Maaloul",
    "Taha Yassine Khenissi",
  ],
  USA: [
    "Christian Pulisic",
    "Gio Reyna",
    "Weston McKennie",
    "Tyler Adams",
    "Tim Weah",
    "Folarin Balogun",
    "Ricardo Pepi",
    "Antonee Robinson",
    "Matt Turner",
    "Sergiño Dest",
    "Yunus Musah",
    "Haji Wright",
    "Johnny Cardoso",
    "Brenden Aaronson",
    "Miles Robinson",
  ],
  Uruguay: [
    "Luis Suárez",
    "Darwin Núñez",
    "Federico Valverde",
    "Ronald Araújo",
    "José María Giménez",
    "Rodrigo Bentancur",
    "Giorgian De Arrascaeta",
    "Facundo Pellistri",
    "Sergio Rochet",
    "Matías Viña",
    "Nicolás de la Cruz",
    "Manuel Ugarte",
  ],
  Wales: [
    "Gareth Bale",
    "Aaron Ramsey",
    "Daniel James",
    "Ben Davies",
    "Kieffer Moore",
    "Neco Williams",
    "Ethan Ampadu",
    "Wayne Hennessey",
    "Harry Wilson",
    "Joe Allen",
    "Connor Roberts",
    "Brennan Johnson",
  ],
  Cameroon: [
    "Vincent Aboubakar",
    "André Onana",
    "Bryan Mbeumo",
    "Karl Toko Ekambi",
    "Frank Anguissa",
    "Collins Fai",
    "Jean-Charles Castelletto",
    "Christian Bassogog",
    "Nicolas N'Koulou",
    "Olivier Ntcham",
    "Georges-Kévin Nkoudou",
    "Eric Maxim Choupo-Moting",
  ],
  "Costa Rica": [
    "Keylor Navas",
    "Joel Campbell",
    "Bryan Ruiz",
    "Celso Borges",
    "Óscar Duarte",
    "Francisco Calvo",
    "Yeltsin Tejeda",
    "Johan Venegas",
    "Anthony Contreras",
    "Ronald Matarrita",
    "Keysher Fuller",
    "Manfred Ugalde",
  ],
  Panama: [
    "Aníbal Godoy",
    "Michael Amir Murillo",
    "José Fajardo",
    "Adalberto Carrasquilla",
    "Ismael Díaz",
    "Luis Mejía",
    "Eric Davis",
    "Rolando Blackburn",
    "Alberto Quintero",
    "Fidel Escobar",
    "César Blackman",
    "José Luis Rodríguez",
  ],
  Paraguay: [
    "Miguel Almirón",
    "Antonio Sanabria",
    "Gustavo Gómez",
    "Ángel Romero",
    "Julio Enciso",
    "Diego Gómez",
    "Omar Alderete",
    "Carlos González",
    "Robert Rojas",
    "Derlis González",
    "Juan Cazares",
    "Santiago Rojas",
  ],
  Peru: [
    "Paolo Guerrero",
    "André Carrillo",
    "Renato Tapia",
    "Gianluca Lapadula",
    "Luis Advíncula",
    "Pedro Aquino",
    "Christian Cueva",
    "Yoshimar Yotún",
    "Pedro Gallese",
    "Alexander Callens",
    "Raúl Ruidíaz",
    "Alex Valera",
  ],
  Sweden: [
    "Alexander Isak",
    "Dejan Kulusevski",
    "Victor Lindelöf",
    "Emil Forsberg",
    "Viktor Gyökeres",
    "Mattias Svanberg",
    "Kristoffer Olsson",
    "Robin Olsen",
    "Marcus Danielson",
    "Jesper Karlsson",
    "Anthony Elanga",
    "Filip Helander",
  ],
  Ukraine: [
    "Oleksandr Zinchenko",
    "Mykhailo Mudryk",
    "Viktor Tsygankov",
    "Ruslan Malinovskyi",
    "Andriy Yarmolenko",
    "Oleksandr Zubkov",
    "Roman Yaremchuk",
    "Anatoliy Trubin",
    "Illia Zabarnyi",
    "Vitaliy Mykolenko",
    "Serhiy Sydorchuk",
    "Artem Dovbyk",
  ],
  Scotland: [
    "Andy Robertson",
    "Kieran Tierney",
    "John McGinn",
    "Scott McTominay",
    "Che Adams",
    "Lyndon Dykes",
    "Ryan Christie",
    "Angus Gunn",
    "Grant Hanley",
    "Lewis Ferguson",
    "Jack Hendry",
    "Billy Gilmour",
  ],
  "Côte d'Ivoire": [
    "Sébastien Haller",
    "Nicolas Pépé",
    "Franck Kessié",
    "Wilfried Zaha",
    "Serge Aurier",
    "Ibrahim Sangaré",
    "Simon Adingra",
    "Yahia Fofana",
    "Odilon Kossounou",
    "Jean-Philippe Krasso",
    "Max-Alain Gradel",
    "Jean Michael Seri",
  ],
  Algeria: [
    "Riyad Mahrez",
    "Ismaël Bennacer",
    "Youcef Atal",
    "Rais M'Bolhi",
    "Adam Ounas",
    "Aissa Mandi",
    "Ramy Bensebaini",
    "Baghdad Bounedjah",
    "Sofiane Feghouli",
    "Youcef Belaïli",
    "Haris Belkebla",
    "Islam Slimani",
  ],
  Nigeria: [
    "Victor Osimhen",
    "Ademola Lookman",
    "Samuel Chukwueze",
    "Alex Iwobi",
    "Wilfred Ndidi",
    "Kelechi Iheanacho",
    "Calvin Bassey",
    "Frank Onyeka",
    "Moses Simon",
    "Taiwo Awoniyi",
    "William Troost-Ekong",
    "Stanley Nwabali",
  ],
  "South Africa": [
    "Percy Tau",
    "Themba Zwane",
    "Ronwen Williams",
    "Thapelo Maseko",
    "Sphelele Mkhulise",
    "Teboho Mokoena",
    "Evidence Makgopa",
    "Grant Kekana",
    "Khuliso Mudau",
    "Mothobi Mvala",
    "Sphephelo Sithole",
    "Bongani Sam",
  ],
  Jamaica: [
    "Leon Bailey",
    "Michail Antonio",
    "Shamar Nicholson",
    "Damion Lowe",
    "Ethan Pinnock",
    "Andre Blake",
    "Bobby Decordova-Reid",
    "Daniel Johnson",
    "Kemar Lawrence",
    "Amari'i Bell",
    "Ricardo Morris",
    "Kaheim Dixon",
  ],
  Haiti: [
    "Duckens Nazon",
    "Frantzdy Pierrot",
    "Derrick Etienne",
    "Steeven Saba",
    "Johny Placide",
    "Zachary Herivaux",
    "Ricardo Adé",
    "Carlens Arcus",
    "Bryan Alceus",
    "Djenepo",
    "Mondy Prunier",
    "Danley Jean Jacques",
  ],
  Curaçao: [
    "Leandro Bacuna",
    "Elson Hooi",
    "Juriën Gaari",
    "Roly Bonevacia",
    "Cuco Martina",
    "Eloy Room",
    "Brandley Kuwas",
    "Gino van Kessel",
    "Jarchinio Antonia",
    "Juriën Gaari",
    "Sherel Floranus",
    "Juriën Gaari",
  ],
  "New Zealand": [
    "Chris Wood",
    "Winston Reid",
    "Marco Rojas",
    "Alex Paulsen",
    "Michael Boxall",
    "Clayton Lewis",
    "Marko Stamenic",
    "Ben Old",
    "Elijah Just",
    "Finn Surman",
    "Kosta Barbarouses",
    "Callan Elliot",
  ],
  Turkey: [
    "Hakan Çalhanoğlu",
    "Arda Güler",
    "Cengiz Ünder",
    "Merih Demiral",
    "Kenan Yıldız",
    "İrfan Can Kahveci",
    "Uğurcan Çakır",
    "Zeki Çelik",
    "Barış Alper Yılmaz",
    "Orkun Kökçü",
    "Kerem Aktürkoğlu",
    "Abdülkerim Bardakcı",
  ],
};

const ALL_PLAYERS: Player[] = Object.entries(SQUADS).flatMap(
  ([country, names]) =>
    Array.from(new Set(names)).map((name) => ({ name, country }))
);

function normalize(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
}

export function searchPlayers(query: string, limit = 50): Player[] {
  const normalizedQuery = normalize(query);
  if (!normalizedQuery) {
    return ALL_PLAYERS.slice(0, limit);
  }

  return ALL_PLAYERS.filter(
    (player) =>
      normalize(player.name).includes(normalizedQuery) ||
      normalize(player.country).includes(normalizedQuery)
  ).slice(0, limit);
}

export function getPlayersForTeams(teams: string[]): Player[] {
  const teamSet = new Set(teams);
  return ALL_PLAYERS.filter((player) => teamSet.has(player.country));
}

export function getPlayerPickerOptions(preferredTeams: string[] = []) {
  const preferred = new Set(preferredTeams);
  const preferredPlayers = ALL_PLAYERS.filter((player) =>
    preferred.has(player.country)
  );
  const otherPlayers = ALL_PLAYERS.filter(
    (player) => !preferred.has(player.country)
  );
  const seen = new Set<string>();

  return [...preferredPlayers, ...otherPlayers]
    .filter((player) => {
      if (seen.has(player.name)) return false;
      seen.add(player.name);
      return true;
    })
    .map((player) => ({
      value: player.name,
      label: player.name,
      hint: player.country,
    }));
}
